import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#3631b4",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb595",
        "on-secondary-container": "#fffbff",
        "on-surface-variant": "#414755",
        "on-primary-container": "#fefcff",
        "on-tertiary-fixed": "#351000",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3034",
        "on-primary-fixed": "#001a41",
        "outline-variant": "#c1c6d7",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed-dim": "#c2c1ff",
        "on-tertiary-container": "#fffbff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f1f0f5",
        "primary-container": "#0070eb",
        secondary: "#4c4aca",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#c64f00",
        "inverse-primary": "#adc6ff",
        "surface-variant": "#e3e2e7",
        "on-tertiary": "#ffffff",
        primary: "#0058bc",
        "surface-container": "#eeedf3",
        "surface-bright": "#faf9fe",
        surface: "#faf9fe",
        "surface-tint": "#005bc1",
        error: "#ba1a1a",
        background: "#faf9fe",
        "surface-container-low": "#f4f3f8",
        "on-surface": "#1a1b1f",
        outline: "#717786",
        "secondary-container": "#6664e4",
        "secondary-fixed": "#e2dfff",
        "on-secondary-fixed": "#0c006a",
        "surface-dim": "#dad9df",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#1a1b1f",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e7",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-high": "#e9e7ed",
        tertiary: "#9e3d00",
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "2rem",
        gutter: "1.5rem",
        "stack-sm": "0.75rem",
        "stack-md": "1.25rem",
        "margin-mobile": "1.5rem",
        "margin-desktop": "4rem",
      },
      fontFamily: {
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        display: ["42px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "500" }],
        "title-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
